AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template demos all the built-in AWS Cloudformation parameter types.
Parameters:
  AvailabilityZoneName:
    Description: AWS::EC2::AvailabilityZone::Name
    Type: AWS::EC2::AvailabilityZone::Name

  # "Note that the AWS CloudFormation console doesn't show a drop-down 
  # list of values for this parameter type." . So what good is it? 
  EC2ImageId:
    Description: AWS::EC2::Image::Id
    Type: AWS::EC2::Image::Id

  EC2InstanceId:
    Description: AWS::EC2::Instance::Id
    Type: AWS::EC2::Instance::Id

  KeyPairName:
    Description: AWS::EC2::KeyPair::KeyName
    Type: AWS::EC2::KeyPair::KeyName

  SecurityGroupName:
    Description: AWS::EC2::SecurityGroup::GroupName
    Type: AWS::EC2::SecurityGroup::GroupName

  SecurityGroupId:
    Description: AWS::EC2::SecurityGroup::Id
    Type: AWS::EC2::SecurityGroup::Id

  SubnetID:
    Description: AWS::EC2::Subnet::Id
    Type: AWS::EC2::Subnet::Id

  VolumeID:
    Description: AWS::EC2::Volume::Id
    Type: AWS::EC2::Volume::Id

  VPCId:
    Description: AWS::EC2::VPC::Id
    Type: AWS::EC2::VPC::Id

  Route53HostedZoneId:
    Description: AWS::Route53::HostedZone::Id
    Type: AWS::Route53::HostedZone::Id

  AZNameList:
    Description: List<AWS::EC2::AvailabilityZone::Name>
    Type: List<AWS::EC2::AvailabilityZone::Name>

  EC2ImageIdList:
    Description: List<AWS::EC2::Image::Id>
    Type: List<AWS::EC2::Image::Id>

  EC2InstanceIdList:
    Description: List<AWS::EC2::Instance::Id>
    Type: List<AWS::EC2::Instance::Id>

  SecurityGroupNameList:
    Description: List<AWS::EC2::SecurityGroup::GroupName>
    Type: List<AWS::EC2::SecurityGroup::GroupName>

  SecurityGroupIdList:
    Description: List<AWS::EC2::SecurityGroup::Id>
    Type: List<AWS::EC2::SecurityGroup::Id>

  SubnetIdList:
    Description: List<AWS::EC2::Subnet::Id>
    Type: List<AWS::EC2::Subnet::Id>

  VolumeIdList:
    Description: List<AWS::EC2::Volume::Id>
    Type: List<AWS::EC2::Volume::Id>

  VPCIdList:
    Description: List<AWS::EC2::VPC::Id>
    Type: List<AWS::EC2::VPC::Id>

  Route53HostedZoneIdList:
    Description: List<AWS::Route53::HostedZone::Id>
    Type: List<AWS::Route53::HostedZone::Id>

Resources:
    MyBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: BMRParameterDemoBucket