---
AWSTemplateFormatVersion: 2010-09-09
Description: |
  A template that demonstrates how to use a macro
Parameters:
  AMI:
    Description: AMI ID for the instance
    Type: String
    Default: ami-0b0dcb5067f052a63
  Subnet:
    Description: Subnet in which to place the resources
    Type: AWS::EC2::Subnet::Id    
Transform: [MyNoChangeMacro]
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMI
      SubnetId:
        Ref: Subnet      
      InstanceType: t3.nano
      'Fn::Transform':   # cfn lint incorrectly flags this
        Name: 'MyNoChangeMacro'